name: gooder_store
description: A port of MobileNativeFoundation Store, a library for loading data from remote and local sources.
version: 0.0.1-dev.2
homepage: https://github.com/btrautmann/store
repository: https://github.com/btrautmann/store


environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  equatable: ^2.0.5
  rxdart: ^0.27.7
  stash: ^4.3.4
  stash_memory: ^4.3.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

