name: store

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
        run: dart format --set-exit-if-changed .
        run: dart analyze
        run: dart test --coverage=coverage/ --test-randomize-ordering-seed random
      - uses: codecov/codecov-action@v2
        with:
          files: coverage/**/lcov.info
