name: store

on:
  push:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: store/

    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1.3
      - run: dart format --set-exit-if-changed .
      - run: dart pub get
      - run: dart analyze
      - run: dart test --coverage=coverage/lcov.info --test-randomize-ordering-seed random
      - run: ls coverage/
      - uses: codecov/codecov-action@v2
        with:
          files: store/coverage/lcov.info
